User info class
Leksha/StudyBuddy pull request #41
Opened 2017-07-08 20:25 UTC by SakiAkizuki

2017-07-08 21:23 UTC, Leksha requested changes

2017-07-08 21:23 UTC, Leksha commented on StudyBuddy/app/src/main/java/uw/studybuddy/Events/EventCreation.java
> +            mDatabase.push().setValue(dataMap).addOnCompleteListener(new OnCompleteListener<Void>() {
We wanted to keep all database-related methods in the `FirebaseInstance` class. We already have a method in `FirebaseInstance` called `addNewEventToDatabase`that does this.

2017-07-08 21:23 UTC, Leksha commented on StudyBuddy/app/src/main/java/uw/studybuddy/MainActivity.java
> +    DatabaseReference mUserRootRef = FirebaseDatabase.getInstance().getReference().child("Users")
Refactor to `FirebaseInstance` class.

2017-07-08 21:23 UTC, Leksha commented on StudyBuddy/app/src/main/res/layout/activity_register.xml
> +        android:hint="Please Type in Your UW Ques ID"
- Quest 
- Just use the `EmptyEmail` string instead

2017-07-08 23:55 UTC, SakiAkizuki commented on StudyBuddy/app/src/main/java/uw/studybuddy/MainActivity.java
> +    DatabaseReference mUserRootRef = FirebaseDatabase.getInstance().getReference().child("Users")
the mUserRootRef have to set here for the value change listener function

2017-07-08 23:59 UTC, merged

2017-07-09 00:21 UTC, Leksha commented on StudyBuddy/app/src/main/java/uw/studybuddy/MainActivity.java
> +    DatabaseReference mUserRootRef = FirebaseDatabase.getInstance().getReference().child("Users")
I meant that this code `FirebaseDatabase.getInstance().getReference().child("Users")` should be in `FirebaseInstance` class

We don't want any database-related code like this part `.child("Users")`in other places.